# Generated by Django 4.0.1 on 2022-03-22 01:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='wishlist',
            old_name='cost',
            new_name='item_cost',
        ),
        migrations.AddField(
            model_name='wishlist',
            name='habit_cost',
            field=models.FloatField(default=1, verbose_name='habit cost'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='wishlist',
            name='habit_item',
            field=models.CharField(default=2, max_length=50),
            preserve_default=False,
        ),
    ]
