# Generated by Django 4.0.1 on 2022-03-25 14:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('main_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='habit',
            name='goal_image',
            field=models.ImageField(default='default.png', upload_to='businesscollector/'),
        ),
        migrations.AlterField(
            model_name='habit',
            name='habit_cost',
            field=models.FloatField(help_text='<p> </br>Please enter your goal and its cost</p>', verbose_name='Cost per use'),
        ),
        migrations.AlterField(
            model_name='habit',
            name='habit_item',
            field=models.CharField(max_length=50, verbose_name='Habit'),
        ),
        migrations.AlterField(
            model_name='habit',
            name='item',
            field=models.CharField(max_length=50, verbose_name='Goal'),
        ),
        migrations.AlterField(
            model_name='habit',
            name='item_cost',
            field=models.FloatField(verbose_name='Cost'),
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Name')),
                ('lastname', models.CharField(max_length=50, verbose_name='Last Name')),
                ('email', models.CharField(max_length=50, verbose_name='Email')),
                ('profile_image', models.ImageField(default='default.png', null=True, upload_to='businesscollector/')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
