# Generated by Django 4.0.1 on 2022-03-22 01:13

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('main_app', '0002_rename_cost_wishlist_item_cost_wishlist_habit_cost_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='WishList',
            new_name='Habit',
        ),
    ]
