# Generated by Django 4.0.1 on 2022-03-24 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_habit_delete_wishlist'),
    ]

    operations = [
        migrations.AddField(
            model_name='habit',
            name='total_saved',
            field=models.FloatField(default=0, verbose_name='total saved'),
        ),
    ]
