# Generated by Django 4.0.1 on 2022-03-24 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_habit_delete_wishlist'),
    ]

    operations = [
        migrations.AlterField(
            model_name='habit',
            name='habit_cost',
            field=models.FloatField(verbose_name='Cost per use'),
        ),
        migrations.AlterField(
            model_name='habit',
            name='habit_item',
            field=models.CharField(max_length=50, verbose_name='Habit'),
        ),
        migrations.AlterField(
            model_name='habit',
            name='item',
            field=models.CharField(max_length=50, verbose_name='Goal'),
        ),
        migrations.AlterField(
            model_name='habit',
            name='item_cost',
            field=models.FloatField(verbose_name='Cost'),
        ),
    ]
