# Generated by Django 4.0.1 on 2022-03-24 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0003_habit_total_saved'),
    ]

    operations = [
        migrations.AddField(
            model_name='habit',
            name='click_count',
            field=models.FloatField(default=0, verbose_name='click count'),
        ),
    ]
