# Generated by Django 4.0.1 on 2022-03-24 07:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0003_habit_contribution_total'),
    ]

    operations = [
        migrations.AddField(
            model_name='habit',
            name='contribution_percentage',
            field=models.FloatField(default=0),
        ),
    ]
