# Generated by Django 4.0.1 on 2022-03-24 21:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0003_profile_profile_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='habit',
            name='habit_cost',
            field=models.FloatField(help_text='<p> </br>Field accepts all uppercase only</p>', verbose_name='Cost per use'),
        ),
    ]
