# Generated by Django 4.0.1 on 2022-03-23 00:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0003_rename_wishlist_habit'),
    ]

    operations = [
        migrations.AddField(
            model_name='habit',
            name='initial_item_cost',
            field=models.FloatField(default=1, verbose_name='initial cost'),
            preserve_default=False,
        ),
    ]
