# Generated by Django 4.0.1 on 2022-03-24 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0003_alter_habit_habit_cost_alter_habit_habit_item_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='habit',
            name='goal_image',
            field=models.ImageField(default='default.png', upload_to='businesscollector/'),
        ),
    ]
