# Generated by Django 4.0.1 on 2022-03-24 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0004_alter_habit_goal_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='habit',
            name='goal_image',
            field=models.ImageField(upload_to='businesscollector/'),
        ),
    ]
