# Generated by Django 4.0.1 on 2022-03-24 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0004_habit_click_count'),
    ]

    operations = [
        migrations.AlterField(
            model_name='habit',
            name='click_count',
            field=models.IntegerField(default=0, verbose_name='click count'),
        ),
    ]
