# Generated by Django 4.0.1 on 2022-03-24 08:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0004_habit_contribution_percentage'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='habit',
            name='contribution_percentage',
        ),
        migrations.RemoveField(
            model_name='habit',
            name='contribution_total',
        ),
    ]
