# Generated by Django 4.0.1 on 2022-03-24 21:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0004_alter_habit_habit_cost'),
    ]

    operations = [
        migrations.AlterField(
            model_name='habit',
            name='habit_cost',
            field=models.FloatField(help_text='<p> </br>Please enter your goal and its cost</p>', verbose_name='Cost per use'),
        ),
    ]
