# Generated by Django 4.0.1 on 2022-03-24 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0005_alter_habit_goal_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='habit',
            name='item',
            field=models.CharField(help_text='test', max_length=50, verbose_name='Goal'),
        ),
    ]
