# Generated by Django 4.0.1 on 2022-03-24 08:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0005_remove_habit_contribution_percentage_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='habit',
            name='badgepercent',
            field=models.FloatField(default=0, verbose_name='badgepercent'),
        ),
    ]
