# Generated by Django 4.0.1 on 2022-03-23 00:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0005_alter_habit_initial_item_cost'),
    ]

    operations = [
        migrations.AlterField(
            model_name='habit',
            name='initial_item_cost',
            field=models.FloatField(null=True, verbose_name='initial cost'),
        ),
    ]
