# Generated by Django 4.0.1 on 2022-03-24 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0006_alter_habit_item'),
    ]

    operations = [
        migrations.AlterField(
            model_name='habit',
            name='habit_cost',
            field=models.FloatField(help_text='Please enter your goal and it’s cost', verbose_name='Cost per use'),
        ),
        migrations.AlterField(
            model_name='habit',
            name='item',
            field=models.CharField(max_length=50, verbose_name='Goal'),
        ),
    ]
