# Generated by Django 4.0.1 on 2022-03-23 00:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0006_alter_habit_initial_item_cost'),
    ]

    operations = [
        migrations.AddField(
            model_name='habit',
            name='completed_goal',
            field=models.BooleanField(default=False),
        ),
    ]
