# Generated by Django 4.0.1 on 2022-03-24 08:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0006_habit_badgepercent'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='habit',
            name='badgepercent',
        ),
        migrations.AddField(
            model_name='habit',
            name='ninety_goal',
            field=models.BooleanField(default=False),
        ),
    ]
