# Generated by Django 4.0.1 on 2022-03-24 18:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0007_alter_habit_habit_cost_alter_habit_item'),
    ]

    operations = [
        migrations.AlterField(
            model_name='habit',
            name='habit_cost',
            field=models.FloatField(help_text=' <br/> Please enter your goal and it’s cost', verbose_name='Cost per use'),
        ),
    ]
