# Generated by Django 4.0.1 on 2022-03-23 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0007_habit_completed_goal'),
    ]

    operations = [
        migrations.AlterField(
            model_name='habit',
            name='habit_cost',
            field=models.FloatField(verbose_name='ESTIMATED COST'),
        ),
        migrations.AlterField(
            model_name='habit',
            name='habit_item',
            field=models.CharField(max_length=50, verbose_name='HABIT NAME'),
        ),
        migrations.AlterField(
            model_name='habit',
            name='item',
            field=models.CharField(max_length=50, verbose_name='NAME'),
        ),
        migrations.AlterField(
            model_name='habit',
            name='item_cost',
            field=models.FloatField(verbose_name='ITEM COST'),
        ),
    ]
