# Generated by Django 4.0.1 on 2022-03-23 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0008_alter_habit_habit_cost_alter_habit_habit_item_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='habit',
            name='goal_image',
            field=models.ImageField(default='default.png', null=True, upload_to='businesscollector/'),
        ),
    ]
