# Generated by Django 4.0.1 on 2022-03-24 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0008_alter_habit_habit_cost'),
    ]

    operations = [
        migrations.AlterField(
            model_name='habit',
            name='habit_cost',
            field=models.FloatField(help_text=' P<br/>lease enter your goal and it’s cost', verbose_name='Cost per use'),
        ),
    ]
