# Generated by Django 4.0.1 on 2022-03-23 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0009_habit_goal_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='habit',
            name='half_goal',
            field=models.BooleanField(default=False),
        ),
    ]
