# Generated by Django 4.0.1 on 2022-03-23 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0010_habit_half_goal'),
    ]

    operations = [
        migrations.AddField(
            model_name='habit',
            name='quarter_goal',
            field=models.BooleanField(default=False),
        ),
    ]
