# Generated by Django 4.0.1 on 2022-03-23 20:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0012_habit_three_quarter_goal'),
    ]

    operations = [
        migrations.AddField(
            model_name='habit',
            name='random_message',
            field=models.CharField(default=1, max_length=220),
            preserve_default=False,
        ),
    ]
