# Generated by Django 4.0.1 on 2022-03-23 20:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0017_alter_habit_random_message'),
    ]

    operations = [
        migrations.AlterField(
            model_name='habit',
            name='random_message',
            field=models.CharField(max_length=220),
        ),
    ]
